"""Shared dashboard configuration definitions.

This module contains the canonical, user-facing guild configuration schema used by
both the static and dynamic dashboard configuration pages.
"""

from __future__ import annotations

from typing import Any

BASE_CONFIG_SCHEMA: dict[str, dict[str, Any]] = {
    "assistant_enabled": {
        "type": "select",
        "label": "Assistant Enabled",
        "description": "Turn the AI assistant on or off for this server.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "assistant_prompt": {
        "type": "textarea",
        "label": "System Prompt",
        "description": "Defines the assistant's tone, rules, and behavior.",
        "placeholder": "You are a helpful assistant...",
        "default": "You are a helpful support assistant. Answer questions clearly and concisely. If you don't know the answer, say so honestly.",
    },
    "assistant_temperature": {
        "type": "select",
        "label": "Temperature",
        "description": "Controls creativity vs consistency in AI responses.",
        "options": [
            {"value": "0.0", "label": "0.0 - Very Deterministic"},
            {"value": "0.1", "label": "0.1 - Mostly Deterministic"},
            {"value": "0.3", "label": "0.3 - Balanced"},
            {"value": "0.5", "label": "0.5 - Creative"},
            {"value": "0.7", "label": "0.7 - Very Creative"},
            {"value": "0.9", "label": "0.9 - Maximum Creativity"},
            {"value": "1.0", "label": "1.0 - Wild Card"},
        ],
        "default": "0.7",
    },
    "assistant_max_tokens": {
        "type": "select",
        "label": "Max Response Tokens",
        "description": "Maximum tokens returned in assistant responses.",
        "options": [
            {"value": "256", "label": "256 - Short"},
            {"value": "512", "label": "512 - Medium"},
            {"value": "1024", "label": "1024 - Long"},
            {"value": "2048", "label": "2048 - Very Long"},
            {"value": "4096", "label": "4096 - Extended"},
        ],
        "default": "1024",
    },
    "assistant_max_retention": {
        "type": "select",
        "label": "Conversation Retention",
        "description": "How many messages the bot keeps in conversation memory.",
        "options": [
            {"value": "10", "label": "10 messages"},
            {"value": "20", "label": "20 messages"},
            {"value": "40", "label": "40 messages"},
            {"value": "60", "label": "60 messages"},
            {"value": "100", "label": "100 messages"},
        ],
        "default": "40",
    },
    "assistant_function_calls": {
        "type": "select",
        "label": "Function Calling",
        "description": "Allow the assistant to use built-in and custom functions.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "assistant_draw_enabled": {
        "type": "select",
        "label": "Image Generation",
        "description": "Allow the assistant to generate images.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "assistant_relatedness": {
        "type": "select",
        "label": "Knowledge Match Threshold",
        "description": "Minimum similarity required before RAG knowledge is injected.",
        "options": [
            {"value": "0.1", "label": "0.1 - Very broad"},
            {"value": "0.2", "label": "0.2 - Broad"},
            {"value": "0.3", "label": "0.3 - Balanced"},
            {"value": "0.4", "label": "0.4 - Focused"},
            {"value": "0.55", "label": "0.55 - Strict"},
            {"value": "0.7", "label": "0.7 - Very strict"},
        ],
        "default": "0.3",
    },
    "assistant_mention": {
        "type": "select",
        "label": "Mention on Reply",
        "description": "Ping users when the assistant replies in chat channels.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "0",
    },
    "assistant_learning_enabled": {
        "type": "select",
        "label": "Adaptive Learning",
        "description": "Let the assistant learn from conversations and ratings.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "mod_mute_duration_minutes": {
        "type": "select",
        "label": "Default Mute Duration",
        "description": "Default length for timeouts when no duration is supplied.",
        "options": [
            {"value": "5", "label": "5 minutes"},
            {"value": "10", "label": "10 minutes"},
            {"value": "15", "label": "15 minutes"},
            {"value": "30", "label": "30 minutes"},
            {"value": "60", "label": "1 hour"},
            {"value": "1440", "label": "1 day"},
            {"value": "10080", "label": "1 week"},
        ],
        "default": "10",
    },
    "mod_max_warnings_before_action": {
        "type": "select",
        "label": "Warnings Before Action",
        "description": "How many warnings trigger the automatic moderation action.",
        "options": [
            {"value": "1", "label": "1 warning"},
            {"value": "2", "label": "2 warnings"},
            {"value": "3", "label": "3 warnings"},
            {"value": "4", "label": "4 warnings"},
            {"value": "5", "label": "5 warnings"},
        ],
        "default": "3",
    },
    "mod_warning_action": {
        "type": "select",
        "label": "Warning Auto-Action",
        "description": "What happens when the warning threshold is reached.",
        "options": [
            {"value": "mute", "label": "Mute"},
            {"value": "kick", "label": "Kick"},
            {"value": "ban", "label": "Ban"},
        ],
        "default": "mute",
    },
    "mod_log_channel": {
        "type": "text",
        "label": "Mod Log Channel ID",
        "description": "Channel where moderation events are logged.",
        "placeholder": "123456789012345678",
    },
    "automod_enabled": {
        "type": "select",
        "label": "Auto-Mod Enabled",
        "description": "Enable spam and filter enforcement.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "automod_spam_threshold": {
        "type": "select",
        "label": "Spam Threshold",
        "description": "Messages sent within the interval before spam is flagged.",
        "options": [
            {"value": "3", "label": "3 messages"},
            {"value": "5", "label": "5 messages"},
            {"value": "7", "label": "7 messages"},
            {"value": "10", "label": "10 messages"},
            {"value": "15", "label": "15 messages"},
        ],
        "default": "5",
    },
    "automod_spam_interval": {
        "type": "select",
        "label": "Spam Interval",
        "description": "Seconds that make up the spam detection window.",
        "options": [
            {"value": "3", "label": "3 seconds"},
            {"value": "5", "label": "5 seconds"},
            {"value": "10", "label": "10 seconds"},
            {"value": "15", "label": "15 seconds"},
            {"value": "30", "label": "30 seconds"},
        ],
        "default": "5",
    },
    "welcome_channel": {
        "type": "text",
        "label": "Welcome Channel ID",
        "description": "Channel where join messages are posted.",
        "placeholder": "123456789012345678",
    },
    "welcome_message": {
        "type": "textarea",
        "label": "Welcome Message",
        "description": "Welcome template. Supports {user}, {username}, and {server}.",
        "placeholder": "Welcome to {server}, {user}!",
    },
    "autorole": {
        "type": "text",
        "label": "Auto-Role ID",
        "description": "Role automatically given to new members.",
        "placeholder": "123456789012345678",
    },
    "verified_role": {
        "type": "text",
        "label": "Verified Role ID",
        "description": "Role granted after rules acceptance.",
        "placeholder": "123456789012345678",
    },
    "ticket_category": {
        "type": "text",
        "label": "Ticket Category ID",
        "description": "Category where support tickets are created.",
        "placeholder": "123456789012345678",
    },
    "ticket_staff_roles": {
        "type": "textarea",
        "label": "Ticket Staff Role IDs",
        "description": "Comma-separated role IDs that can see ticket channels. If empty, roles with Manage Messages are used.",
        "placeholder": "123456789012345678, 987654321098765432",
    },
    "ticket_panel_title": {
        "type": "text",
        "label": "Ticket Panel Title",
        "description": "Title on the Open Ticket panel embed (dashboard or /ticket panel).",
        "placeholder": "Support Tickets",
    },
    "ticket_panel_description": {
        "type": "textarea",
        "label": "Ticket Panel Description",
        "description": "Body text on the ticket panel embed.",
        "placeholder": "Need help? Click the button below…",
    },
    "ticket_panel_footer": {
        "type": "text",
        "label": "Ticket Panel Footer",
        "description": "Small footer line on the ticket panel embed.",
        "placeholder": "One open ticket per user at a time.",
    },
    "reports_channel": {
        "type": "text",
        "label": "Reports Channel ID",
        "description": "Channel where user reports are sent.",
        "placeholder": "123456789012345678",
    },
    "payday_amount": {
        "type": "select",
        "label": "Payday Amount",
        "description": "Daily credits awarded by the economy system.",
        "options": [
            {"value": "50", "label": "50 credits"},
            {"value": "100", "label": "100 credits"},
            {"value": "150", "label": "150 credits"},
            {"value": "200", "label": "200 credits"},
            {"value": "500", "label": "500 credits"},
            {"value": "1000", "label": "1000 credits"},
        ],
        "default": "100",
    },
    "payday_cooldown_hours": {
        "type": "select",
        "label": "Payday Cooldown",
        "description": "Hours between payday collections.",
        "options": [
            {"value": "6", "label": "6 hours"},
            {"value": "12", "label": "12 hours"},
            {"value": "18", "label": "18 hours"},
            {"value": "24", "label": "24 hours"},
        ],
        "default": "24",
    },
    "currency_name": {
        "type": "text",
        "label": "Currency Name",
        "description": "Display name of the server currency.",
        "placeholder": "credits",
        "default": "credits",
    },
    "levels_enabled": {
        "type": "select",
        "label": "Levels Enabled",
        "description": "Enable message XP and level progression.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "levels_announce_channel": {
        "type": "text",
        "label": "Level-Up Announce Channel ID",
        "description": "Channel for level-up notifications. Leave blank to use the message channel.",
        "placeholder": "123456789012345678",
    },
    "levels_cooldown": {
        "type": "select",
        "label": "XP Cooldown",
        "description": "Seconds before a user can earn XP again.",
        "options": [
            {"value": "30", "label": "30 seconds"},
            {"value": "60", "label": "1 minute"},
            {"value": "120", "label": "2 minutes"},
            {"value": "300", "label": "5 minutes"},
        ],
        "default": "60",
    },
    "levels_xp_min": {
        "type": "select",
        "label": "Minimum XP Per Message",
        "description": "Lowest XP award for a qualifying message.",
        "options": [
            {"value": "5", "label": "5 XP"},
            {"value": "10", "label": "10 XP"},
            {"value": "15", "label": "15 XP"},
            {"value": "20", "label": "20 XP"},
            {"value": "25", "label": "25 XP"},
        ],
        "default": "15",
    },
    "levels_xp_max": {
        "type": "select",
        "label": "Maximum XP Per Message",
        "description": "Highest XP award for a qualifying message.",
        "options": [
            {"value": "10", "label": "10 XP"},
            {"value": "15", "label": "15 XP"},
            {"value": "20", "label": "20 XP"},
            {"value": "25", "label": "25 XP"},
            {"value": "30", "label": "30 XP"},
        ],
        "default": "25",
    },
    "levels_exclude_channels": {
        "type": "textarea",
        "label": "Excluded Level Channels",
        "description": "Comma-separated channel IDs that should not award XP.",
        "placeholder": "123456789012345678, 987654321098765432",
    },
    "levels_exclude_roles": {
        "type": "textarea",
        "label": "Excluded Level Roles",
        "description": "Comma-separated role IDs that should not earn XP.",
        "placeholder": "123456789012345678, 987654321098765432",
    },
    "levels_roles": {
        "type": "textarea",
        "label": "Level Role Map",
        "description": "Comma-separated level:role_id pairs, e.g. 5:123...,10:456...",
        "placeholder": "5:123456789012345678, 10:987654321098765432",
    },
    "starboard_enabled": {
        "type": "select",
        "label": "Starboard Enabled",
        "description": "Enable the starboard reaction system.",
        "options": [
            {"value": "1", "label": "Enabled"},
            {"value": "0", "label": "Disabled"},
        ],
        "default": "1",
    },
    "starboard_channel": {
        "type": "text",
        "label": "Starboard Channel ID",
        "description": "Channel where starred messages are reposted.",
        "placeholder": "123456789012345678",
    },
    "starboard_threshold": {
        "type": "select",
        "label": "Starboard Threshold",
        "description": "Number of reactions required before a message is featured.",
        "options": [
            {"value": "1", "label": "1 reaction"},
            {"value": "2", "label": "2 reactions"},
            {"value": "3", "label": "3 reactions"},
            {"value": "5", "label": "5 reactions"},
            {"value": "10", "label": "10 reactions"},
        ],
        "default": "3",
    },
    "starboard_emoji": {
        "type": "text",
        "label": "Starboard Emoji",
        "description": "Emoji users react with to feature a message.",
        "placeholder": "⭐",
        "default": "⭐",
    },
    "starboard_ignore_channels": {
        "type": "textarea",
        "label": "Ignored Starboard Channels",
        "description": "Comma-separated channel IDs ignored by the starboard.",
        "placeholder": "123456789012345678, 987654321098765432",
    },
}

CONFIG_CATEGORIES: dict[str, list[str]] = {
    "AI Assistant": [
        "assistant_enabled",
        "assistant_model",
        "assistant_prompt",
        "assistant_temperature",
        "assistant_max_tokens",
        "assistant_max_retention",
        "assistant_embedding_model",
        "assistant_image_model",
        "assistant_function_calls",
        "assistant_draw_enabled",
        "assistant_relatedness",
        "assistant_mention",
        "assistant_learning_enabled",
    ],
    "Moderation": [
        "mod_mute_duration_minutes",
        "mod_max_warnings_before_action",
        "mod_warning_action",
        "mod_log_channel",
    ],
    "Auto-Moderation": [
        "automod_enabled",
        "automod_spam_threshold",
        "automod_spam_interval",
    ],
    "Welcome & Tickets": [
        "welcome_channel",
        "welcome_message",
        "autorole",
        "verified_role",
        "ticket_category",
        "ticket_staff_roles",
        "ticket_panel_title",
        "ticket_panel_description",
        "ticket_panel_footer",
        "reports_channel",
    ],
    "Economy": [
        "payday_amount",
        "payday_cooldown_hours",
        "currency_name",
    ],
    "Leveling": [
        "levels_enabled",
        "levels_announce_channel",
        "levels_cooldown",
        "levels_xp_min",
        "levels_xp_max",
        "levels_exclude_channels",
        "levels_exclude_roles",
        "levels_roles",
    ],
    "Starboard": [
        "starboard_enabled",
        "starboard_channel",
        "starboard_threshold",
        "starboard_emoji",
        "starboard_ignore_channels",
    ],
}
